[package]
name = "aprilgrid"
version = "0.1.0"
edition = "2021"

[dependencies]
faer = "0.19.4"
geo = "0.28.0"
image = "0.25.4"
imageproc = "0.25.0"
nalgebra = "0.33.2"

[dev-dependencies]
env_logger = "0.11.5"
glob = "0.3.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
rerun = "0.17.0"

[[example]]
name = "demo"
path = "examples/demo.rs"
